### ISSUE TITLE
OctoberCMS 2.0 Compatibility

### ISSUE THREAD

**Issue by abstracttechgroup** [rainlab/blogvideo-plugin#6]
We use this plugin for several client blogs, and it looks like the markdown editor widget in OctoberCMS 2 changed to js rendering only. This is breaking compatibility with this plugin, are there any plans to update it to work with OctoberCMS 2?

**Comment by daftspunk** [comment]
Hi @abstracttechgroup 

We have plans on improving the editing experience, in the meantime, in v1.5.4 of the blog plugin we've made it possible to activate the previous editor. 

Navigate to the Settings to enable the Legacy Markdown Editor and this should continue to work normally for you:

![image](https://user-images.githubusercontent.com/1392869/160019767-4bdd7687-0b41-4a92-aac5-511a2442d652.png)

Best regards
